name: astrogeek
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path: ^1.9.0
  path_provider: ^2.1.3
  get: ^4.6.6
  flutter_svg: ^2.0.10
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  dio: ^5.4.3
  geolocator: ^8.0.0
  geocoding: ^2.0.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icons"
  ios: true
  image_path: "assets/icons/appstore.png"

flutter:
  uses-material-design: true

  assets:
     - assets/constellation_imgs/
     - assets/wallpapers/
     - assets/icons/
     - assets/apod/
     - assets/eclipses/
     - .env

  fonts:
    - family: VAS
      fonts:
        - asset: fonts/VeniteAdoremusStraight-Yzo6v.ttf
        - asset: fonts/Inter-VariableFont_slnt,wght.ttf